server:
  port: ${NOTIFICATION_SERVICE_PORT:8084}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: false

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.devconnect.notification.event
        spring.json.value.default.type: com.devconnect.notification.event.PostCreatedEvent
        spring.json.use.type.headers: false

app:
  openapi:
    server-url: ${OPENAPI_SERVER_URL:http://localhost:8090}
  kafka:
    topics:
      post-events: post-events

eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:false}
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
