server:
  port: ${USER_SERVICE_PORT:8081}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: false

app:
  openapi:
    server-url: ${OPENAPI_SERVER_URL:http://localhost:8090}

spring:
  application:
    name: user-service

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/devconnect_users}
    username: ${POSTGRES_USERNAME:devconnect}
    password: ${POSTGRES_PASSWORD:devconnect}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:false}
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
